package jds.l2infoj.gui.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;

/**
 * Author: VISTALL
 * Company: J Develop Station
 * Date: 05/01/2010
 * Time: 11:34:24
 */
public class LogForm extends JFrame
{
	private static LogForm _instance;
	private JPanel root;
	private JTextPane _edito;

	public static LogForm getInstance()
	{
		if (_instance == null)
		{
			_instance = new LogForm();
		}
		return _instance;
	}

	public LogForm()
	{
		setContentPane(root);

		try
		{
			setIconImage(ImageIO.read(getClass().getResource("/jds/l2infoj/resources/images/icon.png")));
		}
		catch (IOException e)
		{
		}
		setSize(450, 700);
		setTitle("Log List");
		setResizable(false);
	}

	public void log(String txt)
	{
		if (_edito.getText().equalsIgnoreCase(""))
		{
			_edito.setText(txt);
		}
		else
		{
			_edito.setText(_edito.getText() + "\n" + txt);
		}

		_edito.updateUI();
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		root = new JPanel();
		root.setLayout(new GridLayoutManager(1, 1, new Insets(5, 5, 5, 5), -1, -1));
		final JScrollPane scrollPane1 = new JScrollPane();
		scrollPane1.setHorizontalScrollBarPolicy(30);
		scrollPane1.setVerticalScrollBarPolicy(22);
		root.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		_edito = new JTextPane();
		_edito.setEditable(false);
		scrollPane1.setViewportView(_edito);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return root;
	}
}
